version: '3.8'
services:
  # backend:
  #   build:
  #     context: ./server
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - mongo
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
      

